### ISSUE TITLE
Game ID not loading when using USBLoaderGX

### ISSUE THREAD

**Issue by ME1234568** [calvinhendriks/MKW-LAN-Brainslug#5]
Hi, I have been trying to get a lan game working from MKW using Brainslug and USBLoaderGX but I am having the most bizzare issue. Whenever I load Brainslug, it tells me the game id is just "v" (instead of RMCE01) and refuses to load modules (however when I use @lilousky's fork of this repo it says loading modules but they never load). This does not happen when I use the disc. I have not seen anyone else have this problem at all, so it's been really frustrating. This is a dump of the game directly from 2 different discs that I own and are confirmed working. I was interested if either of you guys know what the issue could be. I am loading the game from an sd card instead of a usb if that helps. Here is a picture of whats happening. I'll try running it on my other wiis to see if it does the same thing.

![unnamed](https://github.com/user-attachments/assets/a949cfe1-6f74-499c-8aa2-ccd9f28ec70d)

**Comment by lilousky** [comment]
If your game is on the SD card, it's possible that the breakage comes from the fact both usblgx and bslug are accessing the SD. IIRC, in our original testing for the lan setup, using an SD for usblgx caused issues.
Unfortunately this guide is merely a hacky short-term solution until a better one comes along, like a USB loader with built-in bslug support.

**Comment by ME1234568** [comment]
Thanks a lot this actually worked. However, after loading the module, it shows the safety screen and then shows a black screen. It gets stuck here and doesn't progress. Do you know anything about this issue?

**Comment by ME1234568** [comment]
I actually figured out the issue. The usb was formatted fat32. Formatting as NTFS fixed the issue. I'm closing this issue.
